# Generated by Django 2.2.4 on 2019-09-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20190925_1414'),
        ('feedbacks', '0003_auto_20190925_1407'),
    ]

    operations = [
    ]
