# Generated by Django 2.2.4 on 2019-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_merge_20190926_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('OK', 'ok'), ('SUSPICIOUS', 'suspicious'), ('DELETED', 'deleted'), ('CANCELED', 'canceled')], default='OK', max_length=16),
        ),
    ]
