# Generated by Django 2.2.4 on 2019-08-30 09:23

from django.db import migrations, models
import tools.image_funcs


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190826_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatars/none/default.png', null=True, upload_to=tools.image_funcs.get_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatars/none/default.png', null=True, upload_to=tools.image_funcs.get_image_path),
        ),
    ]
