# Generated by Django 2.2.4 on 2019-08-30 10:19

from django.db import migrations, models
import tools.image_funcs


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190830_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='User/0/default.png', null=True, upload_to=tools.image_funcs.get_image_path),
        ),
    ]
